[Proxies]
# This property is used by the clients to connect to IceStorm.
TopicManager = "IceStorm/TopicManager:default -p 9999"

# Proxies for publishes interfaces
FullPoseEstimationPubPrefix = ""



[Endpoints]
# Endpoints for implements interfaces
Camera360RGB = "tcp -p 0"
KinovaArm = "tcp -p 0"
KinovaArm1 = "tcp -p 0"
Lidar3D = "tcp -p 0"
OmniRobot = "tcp -p 0"




[Period]
Compute = 100
Emergency = 500

[Ice]
Warn.Connections = "0"
Trace.Network = "0"
Trace.Protocol = "0"
MessageSizeMax = "20004800"
